services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:

    KimaiPlugin\CustomExportBundle\:
        resource: '../../*'
        exclude: '../../{Resources}'

    KimaiPlugin\CustomExportBundle\Utils\MPdfConverter:
        arguments: ['%kernel.cache_dir%']
